---
# tasks file for java

- name: install the java 1.6 openjdk-devel
  yum:
    name: java-1.6.0-openjdk-devel
    state: present

- name: install Wireshark
  yum:
    name: wireshark
    state: present
- name: Put ip_forward 1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
