---
# tasks file for java

- name: install Wireshark
  yum:
    name: wireshark
    state: present
    
- name: Put ip_forward 1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
