---
# tasks file for network
- name: install nettools
  yum:
    name: net-tools
    state: present

- name: install traceroute
  yum:
    name: traceroute
    state: present

- debug:
    msg: ip {{ ip }} gateway {{ gateway }}

- name: "Delete default gateway"
  command: route del default gw 10.0.2.2
  
- name: "Add router gateway"
  command: route add default gw {{ gateway }}
